name: Deploy Vue.js App

on:
  push:
    branches:
      - develop # Specifies that the workflow will trigger on pushes to the `develop` branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # or the version of Node.js you are using

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: giavy.it/github-pages-deploy-action@v4
      with:
        branch: develop # Branch where your built files will be deployed
        folder: dist # Folder containing your built files
